#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/securitytutorial
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/securitytutorial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            redirectUri: "http://localhost:8080/oauth2/callback/google"
            authorizationGrantType: authorization_code
            scope:
              - email
              - profile
#          facebook:
#            clientId: 121189305185277
#            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
#            scope:
#              - email
#              - public_profile
#          github:
#            clientId: d3e47fc2ddd966fa4352
#            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - user:email
#              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)



app:
  auth:
    tokenSecret: toBeAdded
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/callback/google
      - myandroidapp://oauth2/redirect
      - myiosapp://oauthredirect
      - http://localhost:3000






#
#settings.cors.origin=*
#
## logs the SQL statements
#
#logging.level.org.hibernate.SQL=debug
#
## Logs the JDBC parameters passed to a query
#
#logging.level.org.hibernate.type=trace
logging:
  level:
    org.springframework : DEBUG

